server:
  port: 8080

application:
  title:
    version: 0.1

spring:
  application:
    name: project-template
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

#Spring Boot admin server
  boot:
    admin:
      client:
        url: http://localhost:8080
  level:
    org:
      springframework:
        security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    packageToScan: com.rishabhtech.project.controller   # Package to scan for API annotations
    pathsToMatch: /api/**                               # Restrict to specific paths
  api-docs:
    enabled: true

# Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, mappings, env,  liquibase
  endpoint:
    health:
      show-details: always

rishabhtech:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://www.rishabhtech.com


